services:
  go:
    build:
      context: .
      dockerfile: ./build/docker/go/Dockerfile
    container_name: "zaketn-guests-api-golang"
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - ./build/docker/postgres/db_data:/var/lib/postgresql/data
    container_name: "zaketn-guests-api-postgres"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
