services:
  go:
    build:
      context: .
      dockerfile: ./build/docker/go/Dockerfile
    container_name: "zaketn-guests-api-golang"
    ports:
      - ${API_PORT}:8000
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
    entrypoint: ["./build/docker/go/migrate.sh"]
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - ./build/docker/postgres/db_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    container_name: "zaketn-guests-api-postgres"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
